# This is manifest for simple-commits a tool to make easy conventional commits
# https://github.com/romancitodev/simple-commits

[git]
skip_preview = true
skip_emojis = true

[[scopes]]
name = "nix"
description = "Modify nix environment"

[[scopes]]
name = "app"
description = "App logic related"

[[scopes]]
name = "layout"
description = "Layouts related"

[[scopes]]
name = "component"
description = "Componentes related"

[[scopes]]
name = "service"
description = "Services and Api connection related"
